name: 'anomaly_detection'
version: '1.0.0'
require-dbt-version: '>=1.0.0'
config-version: 2

packages:
  - package: dbt-anomaly-detection
    version: 1.0.0

# This setting configures which "profile" dbt uses for this project.
profile: 'anomaly_detection'

vars:
  anomaly_detection_aggregation_levels: [4, 8, 12, 24]
  anomaly_detection_prob_thresholds : [0.9999, 0.999999]
  anomaly_detection_horizon: 120
  anomaly_detection_forecast_interval: 10
  anomaly_detection_holiday_region: "CA"
  data_interval: 90

  start_date: "\"2023-02-09\""
  # start_date: "CURRENT_DATE()"

  IQR_coeff: 4.5
  cutoff_count: 50
  recent_event_cutoff: 30
  neg_lower_bound_reset: 2
  bounds_coeff: 1.3

  # sources vars
  source_table: sample_table_mock
  source_name: sampled_data

  # input fields
  collector_tstamp: collector_tstamp #collector timestamps
  event_id: event_id #unique identifiers
  app_event: app_event #aggregation field

  # level of granularity and training interval for ML models
  models:
    1mon_8hr:
      period: "8hr"
      train_interval: 60
    2mon_24hr:
      period: "24hr"
      train_interval: 90
    2mon_12hr:
      period: "12hr"
      train_interval: 90
    2mon_8hr:
      period: "8hr"
      train_interval: 90
    2mon_4hr:
      period: "4hr"
      train_interval: 90
    1mon_4hr:
      period: "4hr"
      train_interval: 60
    1mon_12hr:
      period: "12hr"
      train_interval: 60
    1mon_24hr:
      period: "24hr"
      train_interval: 60
    05mon_4hr:
      period: "4hr"
      train_interval: 30
    05mon_8hr:
      period: "8hr"
      train_interval: 30
    05mon_12hr:
      period: "12hr"
      train_interval: 30
    05mon_24hr:
      period: "24hr"
      train_interval: 30

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

  
models:
  anomaly_detection:
    +materialized: view
    anomaly_detection:
      forecasts:
        +pre-hook:
          - "{{ create_models() }}"
