anomaly_detection:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: ld-snowplow
      dataset: snowplow
      method: service-account
      keyfile: ld-snowplow-747d40fb0718.json
      threads: 4

